---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  chef_omnibus_url: http://www.chef.io/chef/install.sh

platforms:
# - name: naelyn/chef-centos-6.6-current
- name: nrel/CentOS-6.7-x86_64
  driver_config:
    customize:
      memory: 2048
    network:
      # - ['private_network', {ip: '192.168.13.13'}]  ## On Windows, use "forwarded_port"
      - ["forwarded_port", {guest: 8080, host: 9090}]
      - ["forwarded_port", {guest: 80, host: 8000}]
      - ["forwarded_port", {guest: 3306, host: 33060}]
      - ["forwarded_port", {guest: 8081, host: 9091}]

suites:
  - name: default
    run_list:
      - recipe[jserver::default]
    attributes:
