name 'jserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jserver'
long_description 'Installs/Configures jserver'
version '0.1.0'

depends 'yum'
depends 'yum-epel'
depends 'iptables'
depends 'lvm'
depends 'chef-vault'
depends 'java'
depends 'tomcat_latest'
depends 'openssl'
depends 'httpd'
depends 'maven'
depends 'clamav'
depends 'mysql'
depends 'jenkins'
depends 'deploy-play'
depends 'zip'